/**
 * Create command - Generate templates for skills and agents
 */

const chalk = require("chalk");
const fs = require("fs-extra");
const path = require("path");
const inquirer = require("inquirer");
const yaml = require("yaml");

module.exports = async function createCommand(type, name, _options) {
  console.log(chalk.cyan.bold("\n🛠️  ClawFlow Create\n"));

  // 1. Determine Type
  let targetType = type;
  if (!targetType || !["skill", "agent"].includes(targetType.toLowerCase())) {
    const { typeAnswer } = await inquirer.prompt([
      {
        type: "list",
        name: "typeAnswer",
        message: "What do you want to create?",
        choices: [
          { name: "Skill (Executable tool/function)", value: "skill" },
          { name: "Agent (High-level LLM orchestrator)", value: "agent" },
        ],
      },
    ]);
    targetType = typeAnswer;
  } else {
    targetType = targetType.toLowerCase();
  }

  // 2. Determine Name
  let targetName = name;
  if (!targetName) {
    const { nameAnswer } = await inquirer.prompt([
      {
        type: "input",
        name: "nameAnswer",
        message: `Enter ${targetType} name:`,
        default: `my-cool-${targetType}`,
        validate: (input) => {
          if (/^[a-z0-9-_]+$/.test(input)) return true;
          return "Name must be lowercase and contain only alphanumeric characters, dashes, or underscores.";
        },
      },
    ]);
    targetName = nameAnswer;
  }

  const targetDir = path.resolve(process.cwd(), targetName);

  // 3. Check if directory exists
  if (fs.existsSync(targetDir)) {
    const { overwrite } = await inquirer.prompt([
      {
        type: "confirm",
        name: "overwrite",
        message: `Directory ${targetName} already exists. Overwrite?`,
        default: false,
      },
    ]);
    if (!overwrite) {
      console.log(chalk.yellow("Aborted."));
      return;
    }
    await fs.remove(targetDir);
  }

  // 4. Gather Metadata
  const metadata = await inquirer.prompt([
    {
      type: "input",
      name: "description",
      message: "Description:",
      default: `A new ${targetType} created with ClawFlow`,
    },
    {
      type: "input",
      name: "author",
      message: "Author:",
      default: process.env.USER || process.env.USERNAME || "anonymous",
    },
    {
      type: "list",
      name: "language",
      message: "Language:",
      choices: ["TypeScript", "Python"],
      when: targetType === "skill",
    },
    {
      type: "confirm",
      name: "gitInit",
      message: "Initialize a git repository?",
      default: true,
    },
  ]);

  // 5. Generate Files
  try {
    if (targetType === "skill") {
      await generateSkill(targetDir, targetName, metadata);
    } else {
      await generateAgent(targetDir, targetName, metadata);
    }

    // Git Init
    if (metadata.gitInit) {
      try {
        const { execSync } = require("child_process");
        execSync("git init", { cwd: targetDir, stdio: "ignore" });
        console.log(chalk.gray("  ✓ Git repository initialized"));
      } catch (e) {
        console.log(chalk.yellow("  ⚠️  Failed to initialize git repository"));
      }
    }

    console.log(
      chalk.green(`\n✅ ${targetType} "${targetName}" created successfully!`),
    );
    console.log(chalk.gray(`Path: ${targetDir}\n`));
    console.log(chalk.cyan("Next steps:"));
    console.log(chalk.white(`  cd ${targetName}`));
    if (targetType === "skill" && metadata.language === "TypeScript") {
      console.log(chalk.white("  npm install"));
    }
    console.log(
      chalk.white("  Edit skill.yaml/agent.yaml to define your logic\n"),
    );
  } catch (err) {
    console.error(chalk.red("\n❌ Error generating files:"), err.message);
  }
};

async function generateSkill(dir, name, metadata) {
  const isTS = metadata.language === "TypeScript";
  const ext = isTS ? "ts" : "py";

  await fs.ensureDir(dir);
  await fs.ensureDir(path.join(dir, "examples"));

  // skill.yaml
  const skillYaml = {
    name: name,
    version: "1.0.0",
    description: metadata.description,
    author: metadata.author,
    type: "tool",
    runtime: metadata.language.toLowerCase(),
    entry: `index.${ext}`,
    parameters: {
      type: "object",
      properties: {
        input: {
          type: "string",
          description: "Input for the skill",
        },
      },
      required: ["input"],
    },
  };

  await fs.writeFile(path.join(dir, "skill.yaml"), yaml.stringify(skillYaml));

  // Entry file
  let content = "";
  if (isTS) {
    content = `
// ${name} - Generated by ClawFlow
export interface Input {
  input: string;
}

export async function run(params: Input) {
  console.log(\`Running ${name} with input: \${params.input}\`);
  return {
    success: true,
    message: \`Processed: \${params.input}\`,
    timestamp: new Date().toISOString()
  };
}
`;
    // package.json for TS
    const pkgJson = {
      name: name,
      version: "1.0.0",
      description: metadata.description,
      main: "index.ts",
      scripts: {
        test: 'echo "Error: no test specified" && exit 1',
      },
      dependencies: {
        "@types/node": "^20.0.0",
        typescript: "^5.0.0",
      },
    };
    await fs.writeJson(path.join(dir, "package.json"), pkgJson, { spaces: 2 });
  } else {
    content = `
# ${name} - Generated by ClawFlow
import sys
import json
import datetime

def run(params):
    input_str = params.get('input', '')
    print(f"Running ${name} with input: {input_str}")
    
    return {
        "success": True,
        "message": f"Processed: {input_str}",
        "timestamp": datetime.datetime.now().isoformat()
    }

if __name__ == "__main__":
    # For local testing
    test_params = {"input": "Hello from ClawFlow"}
    print(json.dumps(run(test_params), indent=2))
`;
    // requirements.txt for Python
    await fs.writeFile(
      path.join(dir, "requirements.txt"),
      "# Add your dependencies here\n",
    );
  }

  await fs.writeFile(path.join(dir, `index.${ext}`), content.trim());

  // Example
  const example = {
    input: "Hello world",
  };
  await fs.writeJson(path.join(dir, "examples", "basic.json"), example, {
    spaces: 2,
  });

  // README
  await fs.writeFile(
    path.join(dir, "README.md"),
    `# ${name}\n\n${metadata.description}`,
  );
}

async function generateAgent(dir, name, metadata) {
  await fs.ensureDir(dir);
  await fs.ensureDir(path.join(dir, "prompts"));
  await fs.ensureDir(path.join(dir, "tools"));

  // agent.yaml
  const agentYaml = {
    name: name,
    version: "1.0.0",
    description: metadata.description,
    author: metadata.author,
    model: "gpt-4-turbo",
    prompts: {
      system: "prompts/system.md",
      user: "prompts/user.md",
    },
    tools: [
      // 'example-skill'
    ],
    config: {
      temperature: 0.7,
      max_tokens: 1000,
    },
  };

  await fs.writeFile(path.join(dir, "agent.yaml"), yaml.stringify(agentYaml));

  // Prompts
  await fs.writeFile(
    path.join(dir, "prompts", "system.md"),
    `# System Prompt for ${name}\n\nYou are a helpful assistant specialized in...`,
  );
  await fs.writeFile(
    path.join(dir, "prompts", "user.md"),
    `# User Prompt for ${name}\n\nTask: {{input}}`,
  );

  // README
  await fs.writeFile(
    path.join(dir, "README.md"),
    `# ${name} (Agent)\n\n${metadata.description}`,
  );
}
